### PR TITLE
#1 Project setup

### PR DESCRIPTION
**Pull request by ValkovMirec**
This pull request set up foundation for development of component library.

- init project with Vite
- configured lib building for package upload
- installed and configured packages mentioned in BA github docs (ESLint,Prettier)
- Installed react-aria/componets, Tailwind
- initial preview page 
- 3 initial components, one TS typed for test, if TS typing works in consuming project
- updated README with yalc package local upload and linking instructions

### CODE REVIEW

**Review by mpinter — COMMENTED** [review]
:+1: , a good start, from reading what's in here, a few things to clean up:
- clean up the eslintrc, some of the rules are specific to other projects and won't be needed in the lib
- we have a preference for not using `index.tsx` files for the file containing the component, editors tend to fare worse off when the component name is in the path rather than in the file name itself (and you end up with having a lot of "index" files open side by side). If you need directories, it's ok to have `components/Button/Button.tsx`. But I'd argue we often won't need directories, in that case I'd leave it without the parent dir, just as a `components/Button.tsx`
- follow these guidelines when writing components https://bratislava.github.io/frontend/components
- would prefer to clean up the boilerplate brought in by Vite (which we're not using) before merging. Any css, assets, anything else I might have missed.
- please explain (in the files or in README) why we need all three of tsconfig / tsconfig-build / tsconfig-node (or recheck if we need them and edit accordingly).
- since tsconfig can quickly become black magic - please go through all the options we decide to keep in it, and where it isn't obvious comment why we have that config set as it is. Also remove those which are set the same way as default. I.e. "noFallthroughCasesInSwitch" is one of the obvious ones, but I also believe it may be the default as well (if not then nevermind this one, but also consider whether we want it there).
- if there are any commented out code (eslintrc, vite.config.ts, elsewhere), either leave a comment why you are keeping it and what it served, or remove it completely

As part of the initial setup, we'd also like to see how we're planning to share tailwind.config between projects. But this can be addressed in a followup PR as well.

Will try this out locally and possibly add a couple more points. But in general this makes sense 🙂

**Review by mpinter — CHANGES_REQUESTED** [review]
Code looks good but importing into other projects does not seem work following the guide in README, screenshot from trying to use in konto.bratislava

Screenshot 2023-11-15 at 12 06 00


Sidenote - README can contain the exact command wihtout the <library-name> placeholder. I'm not sure if `yalc link` is enough when adding for the first time, perhaps it should be `yalc add` ? But honesltly I don't know, would like to learn.

**Comment by daksas303** [comment]
> Code looks good but importing into other projects does not seem work following the guide in README, screenshot from trying to use in konto.bratislava
> 
> Screenshot 2023-11-15 at 12 06 00
> Sidenote - README can contain the exact command wihtout the placeholder. I'm not sure if `yalc link` is enough when adding for the first time, perhaps it should be `yalc add` ? But honesltly I don't know, would like to learn.

Thats weird. I made slight changes for the build right now, which should allow the dependent app to see the types of our library components. Also, I changed the name from the testing one to the actual one.

I assume you have built the app first before running yalc publish? I tried it now with a clean environment and what I did was: 
`npm run build` in component library
`yalc push --sig` after building in the component library which results in `component-library-bratislava@0.0.1+2a2f9058 published in store.`

Then in the dependent app, I ran
`yalc link component-library-bratislava` which resulted in `Package component-library-bratislava@0.0.1+2a2f9058 linked ==> /Users/dominik.kalamar/Documents/projects/konto.bratislava.sk/next/node_modules/component-library-bratislava`

At this point, I was able to import any component from our library.

image

Maybe there was some mismatch with the build which should be now fixed, or perhaps the naming difference was the issue. Could you kindly try it again and if the issue persists we can look into it deeper to resolve what might be the issue.

Yalc `link` and `add` should be doing a similar thing for us but one or the other should be enough. The difference is that `add` also adds a local path to our library into package.json, which I don't believe is something we want for the testing environment.

**Review by mpinter — APPROVED** [review]
@daksas303 of course I've forgotten to build before publishing 🤦 - thank you, now it works as expected, along with correct type support. Please mention the need to build to the publishing step as well (and add it to the code example before the publish). I guess I won't be the last one who reads just that section of readme without further context when looking for recipe to link to other lib.

A couple more things:
- it's not clear to me from the new section in readme how to use the environmental wrapper. Example is better than text description - please show us the code of the wrapper usage and then of the component used from inside.
- naming: you can name the library @bratislava/component-library. I'd also reconsider the name of the EnvironmentalContext, as there tends to be quite a few top-level providers - https://github.com/bratislava/konto.bratislava.sk/blob/master/next/pages/_app.tsx - it's good to know which belongs to which library at glance. Take inspiration from the naming schemes of some of the existing ones

Once you clean up the above you can merge without further review.

---

Note - I see you're providing Image through the context, I guess that one might have a few more props and can be quite a though one to use universally with & without next/image. Wouldn't go into it in here, just noting it probably won't be as straightforward.

**Pull request merged**
